package org.softgreen.sistcoop.organizacion.client.models;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TransaccionBovedaCaja generated by hbm2java
 */

public interface TransaccionBovedaBovedaModel extends TransaccionInternaModel,
		Model {

	Long getId();

	BigDecimal getSaldoDisponibleOrigen();

	BigDecimal getSaldoDisponibleDestino();

	void setSaldoDisponibleDestino(BigDecimal saldoDisponibleDestino);

	String getOrigen();

	String getObservacion();

	void setObservacion(String observacion);

}
