package org.softgreen.sistcoop.organizacion.client.models;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TransaccionCajaCaja generated by hbm2java
 */

public interface TransaccionCajaCajaModel extends TransaccionInternaModel,
		Model {

	Long getId();

	String getMoneda();

	BigDecimal getSaldoDisponibleOrigen();

	BigDecimal getSaldoDisponibleDestino();

	BigDecimal getMonto();

}
